### ISSUE TITLE
Output option does not affect output file format

### ISSUE THREAD

**Issue by xFrann** [efrecon/sqlite-backup#6]
Hello,

I use the script to backup a data.db file
I would like to use the sqlite3 .backup functionality to back it up using the script.
If I manually use the sqlite3 cli tool when the backup is performed the extension of the file is .db
If I use the backup.sh file from the repo it always outputs with the .sql extension.
This even if I specify the output with -o or --output
I have set the logging as verbose however nothing important is being logged

The output shows:

[backup] [info] [20230509-073202] Starting backup of all databases from /mydirectory/data.db to data-20230509-073202.sql
[backup] [info] [20230509-073202] Backup of /mydirectory/data.db done

I can see from the readme that the .sql output file is a textual sql dumps and not a binary copy.
If I nano into the file I can indeed see it as a collection of queries and not as a binary file.

**Comment by efrecon** [comment]
Use the option `--output db`
